// This file is auto-generated by scripts/generate-version.ts
// Do not edit manually

export const VERSION = {
  git_commit: "3bf3a81",
  git_describe: "v0.17.8-3-g3bf3a81",
  buildTime: "2026-02-13T11:27:38Z",
};
