// This file is auto-generated by scripts/generate-version.ts
// Do not edit manually

export const VERSION = {
  git_commit: "e4d1b36",
  git_describe: "v0.17.8-dirty",
  buildTime: "2026-02-13T09:04:40Z",
};
