// This file is auto-generated by scripts/generate-version.ts
// Do not edit manually

export const VERSION = {
  git_commit: "574739a",
  git_describe: "v0.17.8",
  buildTime: "2026-02-13T09:03:02Z",
};
