"use strict";
// This file is auto-generated by scripts/generate-version.ts
// Do not edit manually
Object.defineProperty(exports, "__esModule", { value: true });
exports.VERSION = void 0;
exports.VERSION = {
    git_commit: "08b959b",
    git_describe: "v0.17.5-1-g08b959b",
    buildTime: "2026-02-12T21:18:03Z",
};
//# sourceMappingURL=version.js.map