"use strict";
// This file is auto-generated by scripts/generate-version.ts
// Do not edit manually
Object.defineProperty(exports, "__esModule", { value: true });
exports.VERSION = void 0;
exports.VERSION = {
    git_commit: "5ec4fd2",
    git_describe: "v0.17.5-dirty",
    buildTime: "2026-02-12T14:24:15Z",
};
//# sourceMappingURL=version.js.map